# -*- coding: utf-8 -*-


from flask import Flask
import os
import psycopg2
from contextlib import closing
from flask import g
import datetime
from flask import render_template
from flask import abort
from flask import request
from flask import url_for
from flask import redirect
from flask import session
from passlib.hash import pbkdf2_sha256
import markdown





DB_SCHEMA = """
DROP TABLE IF EXISTS entries;
CREATE TABLE entries (
    id serial PRIMARY KEY,
    title VARCHAR (127) NOT NULL,
    text TEXT NOT NULL,
    created TIMESTAMP NOT NULL
)
"""

DB_ENTRY_INSERT = """
INSERT INTO entries (title, text, created) VALUES (%s, %s, %s)
"""

DB_ENTRIES_LIST = """
SELECT id, title, text, created FROM entries ORDER BY created DESC
"""

DB_ENTRY_LIST = """
SELECT id, title, text, created FROM entries WHERE entries.id = %s
"""

DB_DELETE_ENTRY_LIST = """
DELETE FROM entries WHERE entries.id = %s
"""

app = Flask(__name__)


def get_entry(id):
    """return a single entry based on id"""
    con = get_database_connection()
    cur = con.cursor()
    cur.execute(DB_ENTRY_LIST, [id])
    keys = ('id', 'title', 'text', 'created')
    row = cur.fetchone()
    cur.execute(DB_DELETE_ENTRY_LIST, [id])
    return dict(zip(keys, row))    # we use fetchone instead of fetch all


def delete_entry_db(id):
    """deletes a single entry based on id"""
    con = get_database_connection()
    cur = con.cursor()
    # cur.execute(DB_ENTRY_LIST, [id])
    # keys = ('id', 'title', 'text', 'created')
    # row = cur.fetchone()
    cur.execute(DB_DELETE_ENTRY_LIST, [id])
    # return dict(zip(keys, row))



def get_all_entries():
    """return a list of all entries as dicts"""
    con = get_database_connection()
    cur = con.cursor()
    cur.execute(DB_ENTRIES_LIST)
    keys = ('id', 'title', 'text', 'created')
    return [dict(zip(keys, row)) for row in cur.fetchall()]

def write_entry(title, text):
    if not title or not text:
        raise ValueError("Title and text required for writing an entry")
    con = get_database_connection()
    cur = con.cursor()
    now = datetime.datetime.utcnow()
    title = markdown.markdown(title)
    text = markdown.markdown(text)
    cur.execute(DB_ENTRY_INSERT, [title, text, now])


@app.route('/edit/<id>', methods=['GET', 'POST'])
def edit_entry(id):
    """return"""
    # Check if session is logged in then serve
    if session['logged_in']:
        entry = get_entry(id)
        entry['text'] = markdown.markdown(entry['text'])
        entry['title'] = markdown.markdown(entry['title'])

        return render_template('edit_form.html', entry=entry)
    else:
        abort(500)

@app.route('/delete/<id>', methods=['GET', 'POST'])
def delete_entry(id):
    """return"""
    # import pdb; pdb.set_trace()
    # Check if session is logged in then serve
    if session['logged_in']:
        delete_entry_db(id)
        # entry['text'] = markdown.markdown(entry['text'])
        # entry['title'] = markdown.markdown(entry['title'])
        return ''
        # return render_template('edit_form.html', entry=entry)
    else:
        abort(500)






@app.route('/show_add_entry')
def show_add_entry():
    return render_template('add_entry.html')

@app.route('/')
def show_entries():
    entries = get_all_entries()
    return render_template('list_entries.html', entries=entries) # we can itteratively entry['text'] = markdown.markdonw(entry['text'],

@app.route('/add', methods=['POST'])
def add_entry():
    try:
        write_entry(request.form['title'], request.form['text'])
    except psycopg2.Error:
        # this will catch any errors generated by the database
        abort(500)
    return redirect(url_for('show_entries'))


@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        try:
            do_login(request.form['username'].encode('utf-8'),
                     request.form['password'].encode('utf-8'))
        except ValueError:
            error = "Login Failed"
        else:
            return redirect(url_for('show_entries'))
    return render_template('login.html', error=error)

@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('show_entries'))


app.config['DATABASE'] = os.environ.get(
    'DATABASE_URL', 'dbname=learning_journal'
)
app.config['ADMIN_USERNAME'] = os.environ.get(
    'ADMIN_USERNAME', 'admin'
)

app.config['ADMIN_PASSWORD'] = os.environ.get(
    'ADMIN_PASSWORD', pbkdf2_sha256.encrypt('admin')
)

app.config['SECRET_KEY'] = os.environ.get(
    'FLASK_SECRET_KEY', 'sooperseekritvaluenooneshouldknow'
)

def connect_db():
    """Return a connection to the configured database"""
    return psycopg2.connect(app.config['DATABASE'])

def init_db():
    """Initialize the database using DB_SCHEMA

    WARNING: executing this function will drop existing tables.
    """
    with closing(connect_db()) as db:
        db.cursor().execute(DB_SCHEMA)
        db.commit()

def get_database_connection():
    db = getattr(g, 'db', None)
    if db is None:
        g.db = db = connect_db()
    return db

@app.teardown_request
def teardown_request(exception):
    db = getattr(g, 'db', None)
    if db is not None:
        if exception and isinstance(exception, psycopg2.Error):
            db.rollback()
        else:
            db.commit()
        db.close()
        g.db = None # get rid of db from the g namespace

def do_login(username='', passwd=''):
    if username != app.config['ADMIN_USERNAME']:
        raise ValueError
    if not pbkdf2_sha256.verify(passwd, app.config['ADMIN_PASSWORD']):
        raise ValueError
    session['logged_in'] = True


if __name__ == '__main__':
    app.run(debug=True, port=5002)
